// Generated by scripts/generate-design-tokens.js. Do not edit.
import 'package:flutter/material.dart';

abstract final class GeneratedTokens {
  static const brand950 = Color(0xFF1A0305);
  static const brand900 = Color(0xFF2A0508);
  static const brand800 = Color(0xFF4A0A10);
  static const brand700 = Color(0xFF7A0F1A);
  static const brand600 = Color(0xFFA3121F);
  static const brand500 = Color(0xFFC8102E);
  static const brand400 = Color(0xFFE23A4A);
  static const brand300 = Color(0xFFF27A83);
  static const brand100 = Color(0xFFFFE5E7);
  static const ember = Color(0xFFFF5A4F);
  static const gold = Color(0xFFFFC857);
  static const lightBackground = Color(0xFFFBF6F5);
  static const lightSurface = Color(0xFFFFFFFF);
  static const lightText = Color(0xFF241014);
  static const lightMuted = Color(0xFF6F5B60);
  static const lightBorder = Color(0xFFEADADD);
  static const darkBackground = Color(0xFF120607);
  static const darkSurface = Color(0xFF1C0B0D);
  static const darkText = Color(0xFFFFF1F1);
  static const darkMuted = Color(0xFFD4B9BD);
  static const darkBorder = Color(0xFF553239);
  static const successLight = Color(0xFF13713A);
  static const successDark = Color(0xFF72DB91);
  static const warningLight = Color(0xFF805600);
  static const warningDark = Color(0xFFFFCB70);
  static const infoLight = Color(0xFF096A86);
  static const infoDark = Color(0xFF70D4F4);
  static const spaceXs = 4.0;
  static const spaceSm = 8.0;
  static const spaceMd = 12.0;
  static const spaceLg = 16.0;
  static const spaceXl = 24.0;
  static const spaceXxl = 32.0;
  static const spaceXxxl = 48.0;
  static const radiusSm = 10.0;
  static const radiusMd = 14.0;
  static const radiusLg = 20.0;
  static const radiusXl = 28.0;
  static const motionFast = Duration(milliseconds: 160);
  static const motionStandard = Duration(milliseconds: 240);
  static const motionEmphasized = Duration(milliseconds: 320);
}
